USE [W_GnBD]
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON AJFAGENTE
REBUILD;
ALTER INDEX ALL ON AJFCLUB
REBUILD;
ALTER INDEX ALL ON AJFCOUNTRY
REBUILD;
ALTER INDEX ALL ON AJFCONTRACT
REBUILD;
ALTER INDEX ALL ON AJFPLAYER
REBUILD;
GO