{
 "title": "Quidgest Logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   { "name": "log_level", "label": "Log Level", "query": "Error,Warning,Info,Debug" }
  ]
 },
 "panels": [
  {
   "title": "Logs Over Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\r\n  count_over_time(\r\n    {service_name=\"$service\", service_instance_id=~\"$instance\"}\r\n    | json\r\n    | detected_level=~\"error|info|warning|debug|critical\" [$__interval]\r\n  )\r\n) by (detected_level)\r\n"
    }
   ]
  },
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"$service\", service_instance_id=~\"$instance\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(\r\n    count_over_time(\r\n      {service_name=\"$service\", service_instance_id=~\"$instance\"}  | json | detected_level=\"error\" [$__interval]\r\n    )\r\n  ) * 100\r\n) / sum(\r\n  count_over_time(\r\n    {service_name=\"$service\", service_instance_id=~\"$instance\"} [$__interval]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Total Count of Errors",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service_name=\"$service\", service_instance_id=~\"$instance\"}  | json | detected_level=\"error\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{service_name=\"$service\", service_instance_id=~\"$instance\"} \r\n| detected_level=~\"(?i)$log_level\""
    }
   ]
  }
 ]
}