{
 "title": "Quidgest Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  {
   "title": "Avg HTTP Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_server_request_duration_seconds_sum{exported_job=\"$instance\"}) by (http_request_method))\r\n/ \r\n(sum(http_server_request_duration_seconds_count{exported_job=\"$instance\"}) by (http_request_method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Avg Menu  Load (ms)",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \r\n  label_replace(\r\n    label_join(\r\n      (max(menu_load_time_milliseconds_sum{exported_job=\"$instance\"}) by (Module, Menu)) / \r\n      clamp_min(max(menu_load_time_milliseconds_count{exported_job=\"$instance\"}) by (Module, Menu), 1),\r\n      \"Menu\", \r\n      \".\",\r\n      \"Module\", \r\n      \"Menu\"\r\n    ),\r\n    \"Module\",\r\n    \"\", \r\n    \"Module\", \r\n    \".*\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Buckets Menu Load ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \r\n  label_replace(\r\n    label_join(\r\n      histogram_quantile(0.99, sum(rate(menu_load_time_milliseconds_bucket{exported_job=\"$instance\"}[$__range])) by (le, Menu, Module)),\r\n      \"Menu\", \r\n      \".\",\r\n      \"Module\",\r\n      \"Menu\"\r\n    ),\r\n    \"Module\",\r\n    \"\", \r\n    \"Module\",\r\n    \".*\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Count  Menu Load",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \r\n  label_replace(\r\n    label_join(\r\n      max(menu_load_time_milliseconds_count{exported_job=\"$instance\"}) by (Menu, Module),\r\n      \"Menu\", \r\n      \".\",\r\n      \"Module\",\r\n      \"Menu\"\r\n    ),\r\n    \"Module\",\r\n    \"\", \r\n    \"Module\",\r\n    \".*\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Avg FormLoad (ms)",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \r\n  (max(form_load_time_milliseconds_sum{exported_job=\"$instance\"}) by (Form)) / \r\n  clamp_min(max(form_load_time_milliseconds_count{exported_job=\"$instance\"}) by (Form), 1)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Bucket Form Load",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \r\n  histogram_quantile(0.99, sum(rate(form_load_time_milliseconds_bucket{exported_job=\"$instance\"}[$__range])) by (le, Form))\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Count Form Load",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \r\n  max(form_load_time_milliseconds_count{exported_job=\"$instance\"}) by (Form)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Avg ManWin Load (ms)",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \r\n  label_replace(\r\n    label_join(\r\n      (max(manua_exec_time_milliseconds_sum{exported_job=\"$instance\"}) by (Name, Parameter)) / \r\n      clamp_min(max(manua_exec_time_milliseconds_count{exported_job=\"$instance\"}) by (Name, Parameter), 1),\r\n      \"Name\", \r\n      \".\",\r\n      \"Name\",\r\n      \"Parameter\"\r\n    ),\r\n    \"Parameter\",\r\n    \"\", \r\n    \"Parameter\",\r\n    \".*\"\r\n  )\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Buket ManWin Load",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \r\n  label_replace(\r\n    label_join(\r\n      histogram_quantile(0.99, sum(rate(manua_exec_time_milliseconds_bucket{exported_job=\"$instance\"}[$__range])) by (le, Name, Parameter)),\r\n      \"Name\", \r\n      \".\",\r\n      \"Name\",\r\n      \"Parameter\"\r\n    ),\r\n    \"Parameter\",\r\n    \"\", \r\n    \"Parameter\",\r\n    \".*\"\r\n  )\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Count ManWin Load",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "\r\ntopk(10, \r\n  label_replace(\r\n    label_join(\r\n      max(manua_exec_time_milliseconds_count{exported_job=\"$instance\"}) by (Name, Parameter),\r\n      \"Name\", \r\n      \".\",\r\n      \"Name\",\r\n      \"Parameter\"\r\n    ),\r\n    \"Parameter\",\r\n    \"\", \r\n    \"Parameter\",\r\n    \".*\"\r\n  )\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Logins",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "group by (User) (login_counter_total{exported_job=\"$instance\", Failed=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}