services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      MSSQL_SA_PASSWORD: "QuidSpark!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "2433:1433"
    volumes:
      #Named volumes are better for executing in different OS
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" -C -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
       
  webadmin:
    build: ../WebAdmin
    container_name: webadmin
    ports:
      - "3031:8080"
    environment:
      CONFIG_PATH: /app/config
    volumes:
      - ../config:/app/config
    depends_on:
      sqlserver:
        condition: service_healthy
      
  genioapp:
    build: .
    container_name: genioapp
    ports:
      - "3030:8080"
    environment:
      CONFIG_PATH: /app/config
    volumes:
      - ../config:/app/config
    depends_on:
      sqlserver:
        condition: service_healthy

volumes:
  sqlserver_data: