packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@quidgest/ui': 0.16.3
  '@vitejs/plugin-vue': 5.2.1
  '@vue/test-utils': 2.4.6
  axios: 1.7.9
  pinia: 2.3.1
  vue: 3.5.13
  vue-router: 4.0.11
  vite: 6.2.2
